language: android
jdk: oraclejdk8

env:
  global:
   - CODECOV = 41ecf180-9727-4d5e-9fb0-dbadd3df31c5

before_install:
  - yes | sdkmanager "platforms;android-27"

before_script:
  - chmod +x gradlew
  - ./gradlew test
  - ./gradlew build
  - ./gradlew connectedAndroidTest

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV
