language: android
jdk: oraclejdk8

before_script:
  - chmod +x gradlew
  - ./gradlew test
  - ./gradlew build
  - ./gradlew connectedAndroidTest

after_success:
  - bash <(curl -s https://codecov.io/bash)
